### ISSUE TITLE
Supporting conda environments

### ISSUE THREAD

**Issue by dmpierre** [ericglau/cairo-ls#18]
Hey :)

`conda` is a very cool package manager, which lets you choose your python version and can be much more flexible than using plain `venv`. I'm actually using the lightweight [miniconda](https://docs.conda.io/en/latest/miniconda.html) version.

I found that to be able to work within my already activated conda env, I simply needed to replace the venv command by `echo`. I guess it still activates a valid command and makes me able to run the cairo language server within my conda env.

Just wanted to share this, in case anyone is looking to do this!

Maybe you/I could add some information in the README?

**Comment by ericglau** [comment]
Thanks for the feedback.

If you are using VS Code, you can go to Settings > Extensions > Cairo LS, and disable the venv checkboxes (for Nile and/or the Cairo/StarkNet compiler) or change the venv commands that are used.

Let me know if that helps and I can add more documentation on these settings.

**Comment by ericglau** [comment]
In that case you can probably just disable the "use venv" checkboxes.

**Comment by dmpierre** [comment]
Yes, seems like a cleaner option indeed :)

Thanks Eric
