### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by FilipLaurentiu** [ericglau/cairo-ls#19]
I got this error. I am running Ubuntu in WSL 2

```
 1: /home/filip/cairo_venv/bin/activate: Permission denied
Cairo LS(CompileError)
```

What persmissions should I set ?

**Comment by ericglau** [comment]
Hi @FilipLaurentiu, can you let me know how you normally run the Cairo/StarkNet compile from WSL 2?  Is it already part of your PATH, or how do you load the Python environment for the compiler?

In VS Code, you can go to Settings > Extensions > Cairo LS, and disable the venv checkboxes (for Nile and/or the Cairo/StarkNet compiler) if the compiler is already part of your PATH.  Or change the venv commands in those settings to whatever command that you are using load the Python environment for the Cairo/StarkNet compiler.

Here is what the default settings look like:
![Screen Shot 2022-03-14 at 11 21 38 AM](https://user-images.githubusercontent.com/29640130/158205229-f8f85f96-95fc-4357-8b1a-9d40979d287a.png)
