### ISSUE TITLE
easy installation with coc?

### ISSUE THREAD

**Issue by amanusk** [ericglau/cairo-ls#30]
Is is possible to make this into "1-step" installation with something like `:CocInstall coc-cairo` ?

**Comment by ericglau** [comment]
This should be possible by creating a Coc plugin.  See [this example](https://samroeca.com/coc-plugin.html#writing-an-extension).

If interested, feel free to give it a try (e.g. as a separate folder in this repo) and submit a PR.  Or you could create one in your own repo and release it on npm.  I think either way would be fine.

**Comment by ericglau** [comment]
I've updated the links in the main readme to point to the above.  Thanks @kevinhalliday for creating it!
