### ISSUE TITLE
Pop up red underline all the time 

### ISSUE THREAD

**Issue by DecentrilizedMan** [ericglau/cairo-ls#35]
when I enable cairo ls extension with another extension called cairo syntax support extension , it pops red underline all the time . It disappears when I disabled this extension .

**Comment by DecentrilizedMan** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/43113774/175779154-5c797a11-e876-4f1c-9643-c6cc34a81685.png">

**Comment by DecentrilizedMan** [comment]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/43113774/175779185-c9c61df2-b540-45e7-b152-00b2d9d5b4df.png">

**Comment by ericglau** [comment]
These extensions should be able to work together.

Did you follow the steps under the Setup section of https://github.com/ericglau/cairo-ls/blob/main/VSCODE.md#setup?  Particularly, do you have a Python virtual env in either `env/bin/activate` or `~/cairo_venv/bin/activate`?

Can you go to Cairo LS in the Output tab at the bottom of VS Code, and provide the logs?  For example:
![cairolsoutput](https://user-images.githubusercontent.com/29640130/175797806-70418fc0-d3df-46d2-9137-76771c44f800.png)

**Comment by DecentrilizedMan** [comment]
I don't use the cairo hint support extension now , and instead follow the instructions  :
<img width="766" alt="image" src="https://user-images.githubusercontent.com/43113774/175798963-d0571c2e-dfbf-4f6f-b573-80fba79c811a.png">
And it worked , both starknet-compile found and have hints when coding

**Comment by ericglau** [comment]
Sounds like it is working for you, so I will close this issue.  Feel free to comment or reopen if you have further concerns.

Just to note, if you are using a custom venv directory, you can customize the settings in the VS Code preferences under Extensions > Cairo LS.  For example, if you are not using Nile, you can disable "Nile Use Venv" and enable "Use Venv", then customize the directory in the "Venv Command" if needed:

![screenshot](https://user-images.githubusercontent.com/29640130/175841985-8a148e5a-31b7-47b4-9743-f287035672ad.png)
