### ISSUE TITLE
Latest version not available on npm 

### ISSUE THREAD

**Issue by kevinhalliday** [ericglau/cairo-ls#39]
It seems the latest version of this package is 0.0.25. But the latest release on npm is [0.0.7](https://www.npmjs.com/package/cairo-ls). Getting the latest version on npm will allow the [coc-cairo plugin](https://github.com/kevinhalliday/coc-cairo) to stay up to date. 

Related coc-cairo issue here: https://github.com/kevinhalliday/coc-cairo/issues/1

**Comment by ericglau** [comment]
There are two different packages, and unfortunately the versioning is a bit confusing:
- The [language server on npm](https://www.npmjs.com/package/cairo-ls) (version 0.0.7) which is defined in https://github.com/ericglau/cairo-ls/blob/main/server/package.json
- The [VS Code extension on VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=ericglau.cairo-ls) (version 0.0.25) which is defined in https://github.com/ericglau/cairo-ls/blob/main/package.json
  - This extension internally uses the same language server as above

So the language server code should be the same, but I'm open to suggestions on how to make this easier to consume.  Examples:
- Keep the language server version and VS Code extension version numbers identical?
- Clearly identify these as separate packages (and include package names in the git tags)?
- Separate out the language server and VS Code extension into different repos?

**Comment by kevinhalliday** [comment]
ah I see. 

I don't see a need to match language server & vs code extension versions. Probably would be more trouble than its worth -  I'm sure there will be extension patches / upgrades that don't concern the language server. Same goes for the coc plugin. 

Separate repos could be nice. It would help make the distinction between the two clearer. And would help break up github issues / PRs into separate buckets. But don't rush on my account.

**Comment by ericglau** [comment]
Thanks for the input.  I'll probably aim to separate the repos at some point.
